### PR TITLE
Add link to rails doc for load config on boot

### PR DESCRIPTION
**Pull request by heliohead**
Add a link to rails documentation usage of load on boot, avoid new users getting warnings on load rails

### CODE REVIEW

**Comment by heliohead** [comment]
W, [2022-04-14T10:20:07.220930 #84269]  WARN -- : DEPRECATION WARNING: Initialization autoloaded the constant Settings.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Settings, for example,
the expected changes won't be reflected in that stale Module object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /Users/helio/foobar/foobar/config/environment.rb:5)
Running via Spring preloader in process 84277
Loading development environment (Rails 6.0.3.6)
irb(main):001:0>

**Comment by heliohead** [comment]
# config/initializers/shortner.rb

Shortener.unique_key_length = 7
Shortener.charset = :alphanumcase
Shortener.default_redirect = Settings.website_base_url

**Comment by heliohead** [comment]
If I Wrap the warning disappear

Rails.application.config.to_prepare do
  Shortener.unique_key_length = 7
  Shortener.charset = :alphanumcase
  Shortener.default_redirect = Settings.website_base_url
end

**Comment by fschwahn** [comment]
@heliohead The warning is caused by your `Settings` class and not related to shortener.

**Comment by heliohead** [comment]
Thanks for response, you are right, I already close the PR

BTW, thank you for your work on this lib 👍

**Pull request closed without merging**
