### PR TITLE
Use browser for bot detection

### LINKED ISSUE #151: Use browser or crawler_detect gem instead of Voight-Kampff gem
This gem uses https://github.com/biola/Voight-Kampff for bot detection. This gem has not been updated in 3 years and is not Ruby 3.0 incompatible. Several PRs and issues have been pending there unaddressed for a long time.

Use the more popular [browser](https://github.com/fnando/browser) or [crawler_detect[(https://github.com/loadkpi/crawler_detect) for the same functionality.

We recently upgraded to ruby 3.0.3, and [File.exists? deprecation warning](https://github.com/biola/Voight-Kampff/pull/49) from kampff gem are flooding the logs.

### PR DESCRIPTION
**Pull request by egeek**
Closes #151 

The `Voight-Kampff` gem is not supported in Ruby 3.2.0 due to the removal of `File.exists?`. This Pull Request replaces `Voight-Kampff` with `browser` which is supported.

### CODE REVIEW

**Comment by Blayr** [comment]
@egeek @jpmcgrath Voight-Kampff 1.3 and above do not have the `File.exists?` issue (Ruby 3 deprecated `File.exists?`).
https://github.com/biola/Voight-Kampff/blob/v1.1.3/lib/voight_kampff/test.rb#L36

I think we can resolve this issue by just bumping the version number of the Voight-Kampff dependency.

**Comment by egeek** [comment]
That'd also work.

We've been using my patched version in production for the past week or so (the one in this PR) and it's been working ok. But @Blayr 's suggestion looks good too.

**Comment by Blayr** [comment]
Looks like I actually needed to upgrade to 2.0
https://github.com/jpmcgrath/shortener/pull/158

**Comment by fschwahn** [comment]
Thank you for your contribution, decided to go with the (now released) update to the original gem.

**Pull request closed without merging**
