### PR TITLE
Try catch error on non unique unique key

### PR DESCRIPTION
**Pull request by asok**
@jpmcgrath this spec should cover it https://github.com/jpmcgrath/shortener/blob/master/spec/models/shortened_url_spec.rb#L124-L135 wouldn't you agree?

### CODE REVIEW

**Comment by asok** [comment]
@craigmcnamara I've added test and parameterize the number of tries.
Also I've changed the implementation that so the retry and re-generation takes place in the `around_create` callback. My former implementation was not working properly when setting the `custom_key` argument.

**Comment by igor04** [comment]
this fix does not resolve `unique_key` uniqueness exception, instead we have `ActiveRecord::StatementInvalid: PG::InFailedSqlTransaction` which is triggered by `retry` as result to perform insert in same transaction #108

**Comment by asok** [comment]
The issue is described [here](https://api.rubyonrails.org/v5.0/classes/ActiveRecord/Transactions/ClassMethods.html#module-ActiveRecord::Transactions::ClassMethods-label-Exception+handling+and+rolling+back).
Basically in Postgres if there's an error in transaction, this transaction needs to be restarted. `Shortener::ShortenedUrl#generate_unique_key` is `around_save` callback wrapped in a transaction started on active record's `#save` method.
I think that the "retry" block needs to be placed outside of the active record's callback, so the transaction can be `ROLLBACK`ed.

**Comment by asok** [comment]
I've made another PR that addresses this issue in #109

**Comment by igor04** [comment]
@asok it looks simpler not to use `rescue` and just fix previous implementation with `exists` query which need to be `unscoped` because scope used in `where` condition before `create|first_or_create` is propagated and `exists?` returns wrong results, so it needs to be: `self.class.unscoped.exists?`

**Comment by asok** [comment]
@igor04 I think that the core issue is described here: [https://robots.thoughtbot.com/the-perils-of-uniqueness-validations]. In a multi threaded/process environment there is a race condition for checking for the uniqueness of the key and saving it.
The only proper way of solving it is catching the `Activerecord::RecordNotUnique` error.

**Comment by asok** [comment]
> but current issue was received not because of race condition, it was received because of exists? query which was wrong and key generated long time ago wasn't detected

@igor04 What do you mean by "current issue"? Do you mean the issue described in your [comment](https://github.com/jpmcgrath/shortener/pull/106#issuecomment-449719986)? I think this was because of the a second attempt of `INSERT` which is not allowed within a failed transaction in Postgres.

**Comment by igor04** [comment]
@asok under `current issue` I mean this one, #106

**Comment by 11factory** [comment]
@igor04 any idea when it will get released ?

**Comment by igor04** [comment]
@11factory I think only maintainers could answers on your question

**Comment by asok** [comment]
Maybe I should write down couple of explanations so we're on the same page:

* This PR fixes the race condition described [here](https://thoughtbot.com/blog/the-perils-of-uniqueness-validations) for MySQL and SQLite databases.
* On Postgres this issue still exists. Though, in case of a collision on the unique key, instead of `ActiveRecord::RecordNotUnique` the thrown error will be `ActiveRecord::StatementInvalid`.
* The new issue is addressed in #109. Unfortunately it potentially contains a breaking change that is described here: https://github.com/jpmcgrath/shortener/pull/109#issue-240779127. I wrote potentially because it depends, if bypassing `Shortener::ShortenedUrl.generate` and creating  `Shortener::ShortenedUrl` "manually" is considered as a part of a "public" interface of this library or not.

**Pull request merged**
