### PR TITLE
little update for rails5

### PR DESCRIPTION
**Pull request by JerryGreen**

### CODE REVIEW

**Comment by JerryGreen** [comment]
whoops, there's a bit more changes than I supposed

**Comment by craigmcnamara** [comment]
Here is a comprehensive pull request for Rails 5 and beyond.

https://github.com/jpmcgrath/shortener/pull/95

**Comment by craigmcnamara** [comment]
Rails 5 support just landed and was released. This can be considered closed.

**Comment by jpmcgrath** [comment]
@JerryGreen thanks for your contribution. Rails5 support is now released in v0.7.1 of the gem.

**Pull request closed without merging**
