### PR TITLE
Made the default redirection url configurable.

### PR DESCRIPTION
**Pull request by jeffheifetz**

### CODE REVIEW

**Comment by kieranklaassen** [comment]
I need this, please merge or comment. Thanks Jeff.

**Comment by aksh0925** [comment]
+1

**Comment by reubenbrown** [comment]
+1 Currently using a hack-y workaround to this issue in some projects I'm working on, would be much more preferable to configure that sort of logic this way

**Comment by pelletencate** [comment]
+1 @kieranklaassen This is amazing, I was just browsing the forks to see if anyone fixed it while you were submitting this pull request. I'd love to use the official repo! Please merge!

**Comment by jpmcgrath** [comment]
Sorry for the silence on this, am going to get this merged today.

**Comment by jpmcgrath** [comment]
@jeffheifetz thank you so much for this addition. I have released version 0.4.0 of Shortener, with your default redirection url functionality. Cheers.

**Pull request merged**
